apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goapp
  labels:
    service: goapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: goapp
    spec:
      containers:
      - name: gotest
        image: "DataXchain/chaincode:latest"
        command: ["sleep"]
        args: ["1000000"]
        imagePullPolicy: Always 
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: goapp
  namespace: default
spec:
  #type: LoadBalancer
  ports:
    - port: 5000
      name: tmp-port
      targetPort: 5000
      #nodePort: 31641
  selector:
    service: goapp
